version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_app
    ports:
      - "8888:80"   # Map localhost:8000 to the container's port 80
    volumes:
      - ./app:/var/www/html  # Mount app directory for live updates
    depends_on:
      - db  # Ensure the database starts first

  db:
    image: mysql:latest
    container_name: mysql_db
    ports:
      - "3306:3306"  # Expose MySQL on localhost:3306
    environment:
      MYSQL_ROOT_PASSWORD: root  # Set a root password
      MYSQL_DATABASE: sudoku              # Database name
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "8080:80"  # Map localhost:8080 to the container's port 80
    environment:
      PMA_HOST: db  # Connect to the MySQL container

volumes:
  db_data:  # Persistent database storage
